CRM/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # 登录，注册，注销，忘记密码，验证码
    path('login/', views.login, name='login'),
    path('get_valid_code/', views.get_valid_code, name='valid_code'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('sign_out/', views.logout, name='sing_out'),

    # 首页
    path('index/', views.index, name='index'),
    path('', views.login),

    # 客户管理
    path('customer/', views.CustomerView.as_view(), name='customer'),
    path('customer/all/', views.CustomerView.as_view(), name='customer_all'),
    path('customer/add/', views.AddEditCustomerView.as_view(), name='customer_add'),
    # 添加公有用户
    path('customer/public_add/', views.AddEditCustomerView.as_view(), name='customer_public_add'),
    path('my_customer/', views.CustomerView.as_view(), name='my_customer'),
    re_path('^customer/edit/(\d+)/$', views.AddEditCustomerView.as_view(), name='customer_edit'),

    # 跟进记录管理
    path('consult_record/', views.ConsultRecordView.as_view(), name='consult_record'),
    path('consult_record/add/', views.AddEditConsultRecordView.as_view(), name='consult_record_add'),
    re_path('^consult_record/edit/(\d+)/$', views.AddEditConsultRecordView.as_view(), name='consult_record_edit'),

    # 财务管理
    path('payment/', views.PaymentView.as_view(), name='payment'),

    # 学生管理
    re_path(r'^', include('student_manage.urls')),

    # 统计数据
    path('count/customer/', views.CountCustomerView.as_view(), name='count_customer'),

    # 权限分配
    re_path(r'^', include(('rbac.urls', 'rbac'),namespace='rbac')),

]

rbac/urls.py
from django.urls import path, re_path, reverse
from rbac import views

urlpatterns = [
    # 权限分配
    path('permission/patch/', views.PermissionPatch.as_view(), name='permission_patch'),
    path('show_permission_menu/', views.PermissionMenu.as_view(), name='show_permission_menu'),

    # 菜单管理
    re_path(r'^permission_menu/delete/(\d+)$', views.PermissionMenu.as_view(), name='permission_menu_delete'),

    # url管理
    re_path(r'^show_permission_url/(\d+)/$', views.PermissionUrl.as_view(), name='show_permission_url')


]

rbac/models.py
from django.db import models
from app01.models import Position


# Create your models here.

class Menu(models.Model):
    """
    菜单列表标题
    """
    title = models.CharField(max_length=32, verbose_name='菜单')
    icon = models.CharField(max_length=32, verbose_name='图标', null=True, blank=True)
    menu_id = models.CharField(max_length=32, verbose_name='菜单id名', default='暂无')

    def __str__(self):
        return self.title


class Permission(models.Model):
    """
    权限表（二级菜单表）
    """
    title = models.CharField(max_length=32, verbose_name='标题')
    url = models.CharField(max_length=60, verbose_name='权限')
    menu = models.ForeignKey("Menu", on_delete=models.CASCADE, null=True, blank=True)
    positions = models.ManyToManyField('app01.Position', verbose_name='职位所拥有的权限', blank=True)
    pid = models.ForeignKey('Menu', related_name='classify', verbose_name='url分类', on_delete=models.CASCADE, null=True,
                            blank=True)
    related_name = models.CharField(max_length=32, verbose_name='别名', null=True,blank=True)

    def __str__(self):
        return self.title

rbac/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.views import View
from rbac.models import Permission, Menu
from app01.models import UserInfo, Department, Position
from django.forms.models import modelformset_factory
from rbac.utils.forms_check import PermissionMenuMF, PermissionUrlMF


# Create your views here.

class PermissionPatch(View):
    def get(self, request):
        # 权限数据
        p_list = {}
        menu_list = Menu.objects.all()
        permission_other_list = Permission.objects.filter(pid__isnull=True)
        p_list['其他'] = permission_other_list
        for item in menu_list:
            permission_list = Permission.objects.filter(pid=item)
            p_list[item.title] = permission_list

        # 部门职位数据
        r_list = {}
        depart_list = Department.objects.all()
        for item in depart_list:
            position_list = Position.objects.filter(depart=item)
            r_list[item.name] = position_list

        # 用户数据
        user_list = UserInfo.objects.all()

        # 选中用户角色部门信息
        uid = request.GET.get('uid')
        if uid and uid.isdigit():
            user_positions_list = UserInfo.objects.filter(pk=uid).values('positions')
        else:
            user_positions_list = []
        user_positions_list = [item['positions'] for item in user_positions_list]

        # 选中用户权限信息

        pid = request.GET.get('pid')
        if user_positions_list:
            permission_list = Position.objects.filter(pk__in=user_positions_list).values('permission').distinct()
        elif pid and pid.isdigit():
            permission_list = Position.objects.filter(pk=pid).values('permission').distinct()
        else:
            permission_list = None

        if permission_list:
            permission_list = [item['permission'] for item in permission_list]
        else:
            permission_list = []

        return render(request, 'permission_patch.html',
                      {'p_list': p_list,
                       'r_list': r_list,
                       'user_list': user_list,
                       'user_positions_list': user_positions_list,
                       'permission_list': permission_list,
                       'uid': int(uid) if user_positions_list else None,
                       'pid': int(pid) if pid and permission_list else None
                       })

    def post(self, request):
        if request.POST.get('action') == 'user_position':
            uid = request.POST.get('user_id')
            position_list = request.POST.getlist('position', [])
            user_obj = UserInfo.objects.filter(pk=uid).first()
            user_obj.positions.set(position_list)
        elif request.POST.get('action') == 'position_permission':
            pid = request.POST.get('pid')
            permission_list = request.POST.getlist('permission')
            position_obj = Position.objects.filter(pk=pid).first()
            if position_obj:
                position_obj.permission_set.set(permission_list)

        return redirect(request.get_full_path())


class PermissionMenu(View):

    def get(self, request):
        # 删除菜单
        del_action = request.GET.get('del')
        if del_action:
            Menu.objects.filter(pk=del_action).delete()
            return redirect('rbac:show_permission_menu')
        parms = list(request.GET.values())
        menu_obj = Menu.objects.all()
        model_formset_menu = modelformset_factory(model=Menu, form=PermissionMenuMF, extra=0)
        formset = model_formset_menu(queryset=menu_obj)
        add_forms = PermissionMenuMF()
        return render(request, 'permission_menu.html',
                      {'formset': formset, 'add_forms': add_forms, 'menu_obj': menu_obj, 'parms': parms})

    def post(self, request):
        parms = list(request.GET.values())
        menu_obj = Menu.objects.all()
        action = request.GET.get('action')
        if action == 'add':
            add_forms = PermissionMenuMF(request.POST)
            if add_forms.is_valid():
                add_forms.save()
                return redirect('rbac:show_permission_menu')
            else:
                return render(request, 'permission_menu.html',
                              {'add_forms': add_forms, 'parms': parms, 'menu_obj': menu_obj})
        elif action == 'edit':
            model_formset_menu = modelformset_factory(model=Menu, form=PermissionMenuMF, extra=0)
            formset = model_formset_menu(request.POST)
            if formset.is_valid():
                formset.save()
                return redirect('rbac:show_permission_menu')
            else:
                return render(request, 'permission_menu.html', {'formset': formset, 'parms': parms})


class PermissionUrl(View):
    def get(self, request, mid):
        parms = list(request.GET.values())
        parms_length = len(parms)
        print(parms_length)
        permission_url_list = Permission.objects.filter(pid_id=mid)
        url_formset = modelformset_factory(model=Permission, form=PermissionUrlMF, extra=0)
        formset = url_formset(queryset=permission_url_list)
        add_forms = PermissionUrlMF()
        return render(request, 'permission_url.html', locals())

    def post(self, request, mid):
        parms = list(request.GET.values())
        action = request.GET.get('action')
        if action == 'edit':
            url_formset = modelformset_factory(model=Permission, form=PermissionUrlMF, extra=0)
            formset = url_formset(request.POST)
            if formset.is_valid():
                formset.save()
                return redirect('{}?next={}'.format(request.path, reverse('rbac:show_permission_menu')))
            else:
                return render(request, 'permission_url.html', locals())
        if action == 'add':
            add_forms = PermissionUrlMF(request.POST)
            if add_forms.is_valid():
                add_forms.save()
                return redirect('{}?next={}'.format(request.path, reverse('rbac:show_permission_menu')))
            else:
                return render(request, 'permission_url.html', locals())

rbac/templates/menu.html
<ul class="am-list admin-sidebar-list">
    <li><a href="{% url 'index' %}"><span class="am-icon-home"></span> 首页</a></li>
    {% for item in permission_menu_dict.values %}
        <li class="admin-parent">
            <a class="am-cf {{ item.menu_style.0 }}" data-am-collapse="{target: '#{{ item.menu_id }}'}"><span
                    class="am-icon-file"></span>
                {{ item.menu_title }} <span class="am-icon-angle-right am-fr am-margin-right"></span></a>
            <ul class="am-list am-collapse admin-sidebar-sub {{ item.menu_style.1 }}" id="{{ item.menu_id }}">
                {% for menu in item.secondary_menu %}
                    <li class="{{ menu.url_style }}"><a href="{{ menu.url }}"><span class="am-icon-check"></span> {{ menu.title }}</a></li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

rbac/templates/permission_menu.html
{% extends 'base.html' %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">权限菜单</strong> /
            <small>权限管理</small>
        </div>
    </div>

    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6 am-form-group">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">

                    <a class="am-btn am-btn-default"
                       href="?action=add"><span
                            class="am-icon-plus"></span>
                        新增</a>
                    <a class="am-btn am-btn-default"
                       href="?action=edit"><span
                            class="am-icon-plus"></span>
                        编辑</a>
                </div>
            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-3">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form" method="post">
                {% csrf_token %}
                {{ formset.management_form }}
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="am-text-center">菜单名称</th>
                        <th class="am-text-center">图标样式</th>
                        <th class="am-text-center">菜单标签ID</th>
                        {% if not parms %}
                            <th class="am-text-center">url管理</th>
                            <th class="am-text-center">删除</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% if 'add' in parms %}
                        <tr>
                            <td>{{ add_forms.title }}</td>
                            <td>{{ add_forms.icon }}</td>
                            <td>{{ add_forms.menu_id }}</td>
                        </tr>
                    {% endif %}
                    {% if 'edit' in parms %}
                        {% for item in formset %}
                            {{ item.id }}
                            <tr>
                                <td>{{ item.title }}</td>
                                <td>{{ item.icon }}</td>
                                <td>{{ item.menu_id }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        {% for item in menu_obj %}
                            <tr>
                                <td>{{ item.title }}</td>
                                <td>{{ item.icon }}</td>
                                <td>{{ item.menu_id }}</td>
                                {% if not parms %}
                                    <td><a href="{% url 'rbac:show_permission_url' item.pk %}?next={{ request.path }}">url详情</a>
                                    </td>
                                    <td>
                                        <div class="am-btn-group am-btn-group-xs">
                                            <a href="?del={{ item.pk }}"
                                               onclick="if(confirm('删除后菜单下的所有url也会删除，确认删除吗？')==false)return false;"
                                               class="am-btn am-btn-default am-btn-xs am-text-secondary">
                                                删除
                                            </a>
                                        </div>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
                {% if parms %}
                    <div class="am-g">
                        <div class="am-u-sm-12 am-u-md-2 am-fr am-form-group">
                            <div class="am-btn-group am-btn-group-xs am-fr">
                                <a class="am-btn am-btn-default" href="?">取消</a>
                                <input type="submit" class="am-btn am-btn-success">
                            </div>
                        </div>
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

rbac/templates/permission_patch.html
{% extends 'base.html' %}


{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">权限分配</strong> /
            <small>权限管理</small>
        </div>
    </div>
    <hr>
    <div class="am-g">
        <div class="am-u-sm-3">
            <div class="am-tab-panel">
                <table class="am-table am-table-bordered am-table-radius">
                    <tbody>
                    <th>用户管理</th>
                    <tr>
                        <td>
                            <ul>
                                {% for user in user_list %}
                                    <li>
                                        {% if uid == user.pk %}
                                            <a href="?uid={{ user.pk }}" style="color: red">{{ user }}</a>
                                        {% else %}
                                            <a href="?uid={{ user.pk }}">{{ user }}</a>
                                        {% endif %}

                                    </li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>

        </div>

        <div class="am-u-sm-4">
            <div class="am-tab-panel">
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="user_position">
                    <input type="hidden" name="user_id" value="{{ uid }}">
                    <table class="am-table am-table-bordered am-table-radius">
                        <tbody>
                        <th>部门职位管理</th>
                        {% if uid %}
                            <th><input type="submit" class="am-btn am-btn-success am-btn-sm"></th>
                        {% endif %}
                        {% for k,v in r_list.items %}
                            <tr class="am-active">
                                <td>
                                    {{ k }}
                                <td>
                            </tr>

                            <tr>

                                <td>
                                    {% for values in v %}
                                        <div>
                                            {% if values.pk in user_positions_list %}
                                                <input type="checkbox" name="position" id="position_{{ values.pk }}"
                                                       value="{{ values.pk }}" checked>
                                            {% else %}
                                                <input type="checkbox" name="position" id="position_{{ values.pk }}"
                                                       value="{{ values.pk }}">
                                            {% endif %}
                                            {% if pid == values.pk %}
                                                <a href="?pid={{ values.pk }}" style="color: red"><label
                                                        for="">{{ values }}</label></a>
                                            {% else %}
                                                <a href="?pid={{ values.pk }}"><label
                                                        for="">{{ values }}</label></a>

                                            {% endif %}


                                        </div>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>

        </div>
        <div class="am-u-sm-5">
            <div class="am-tab-panel">
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="position_permission">
                    <input type="hidden" name="pid" value="{{ pid }}">

                    <table class="am-table am-table-bordered am-table-radius">
                        <tbody>
                        <th>权限管理</th>
                        {% if pid %}
                            <th><input type="submit" class="am-btn am-btn-success am-btn-sm"></th>
                        {% endif %}
                        {% for k,v in p_list.items %}
                            <tr class="am-active">
                                <td>
                                    {{ k }}
                                <td>
                            </tr>

                            <tr>
                                <td>
                                    {% for values in v %}
                                        <div style="display: inline-block">
                                            {% if values.pk in permission_list %}
                                                <input type="checkbox" name="permission" id="permission_{{ values.pk }}"
                                                       value="{{ values.pk }}" checked>
                                            {% else %}
                                                <input type="checkbox" name="permission" id="permission_{{ values.pk }}"
                                                       value="{{ values.pk }}">
                                            {% endif %}

                                            <label for="permission_{{ values.pk }}">{{ values }}</label>
                                        </div>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>

        </div>
    </div>










{% endblock %}

rbac/templates/permission_url.html
{% extends 'base.html' %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">权限路由</strong> /
            <small>权限管理</small>
        </div>
    </div>

    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6 am-form-group">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">

                    <a class="am-btn am-btn-default"
                       href="?action=add&next={% url 'rbac:show_permission_menu' %}"><span
                            class="am-icon-plus"></span>
                        新增</a>
                    <a class="am-btn am-btn-default"
                       href="?action=edit&next={% url 'rbac:show_permission_menu' %}"><span
                            class="am-icon-plus"></span>
                        编辑</a>
                    <a class="am-btn am-btn-default"
                       href="{% url 'rbac:show_permission_menu' %}"><span
                            class="am-icon-plus"></span>
                        返回</a>
                </div>
            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-3">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form" method="post">
                {% csrf_token %}
                {{ formset.management_form }}
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="am-text-center">url标题</th>
                        <th class="am-text-center">url</th>
                        <th class="am-text-center">菜单权限</th>
                        <th class="am-text-center">所属菜单</th>
                        <th class="am-text-center">url别名</th>
                        {% if parms_length == 1 %}
                            <th class="am-text-center">操作</th>
                        {% endif %}


                    </tr>
                    </thead>
                    <tbody>
                    {% if 'add' in parms %}
                        <tr>
                            <td>{{ add_forms.title }}</td>
                            <td>{{ add_forms.url }}</td>
                            <td>{{ add_forms.menu }}</td>
                            <td>{{ add_forms.pid }}</td>
                            <td>{{ add_forms.related_name }}</td>
                        </tr>
                    {% endif %}
                    {% if 'edit' in parms %}
                        {% for item in formset %}
                            {{ item.id }}
                            {{ item.positions }}
                            <tr>
                                <td>{{ item.title }}</td>
                                <td>{{ item.url }}</td>
                                <td>{{ item.menu }}</td>
                                <td>{{ item.instance.pid }}</td>
                                <td>{{ item.related_name }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        {% for item in permission_url_list %}

                            <tr>
                                <td>{{ item.title }}</td>
                                <td>{{ item.url }}</td>
                                <td>{{ item.menu|default:'非菜单权限' }}</td>
                                <td>{{ item.pid }}</td>
                                <td>{{ item.related_name }}
                                    {% if parms_length == 1 %}
                                        <td>
                                            <div class="am-btn-group am-btn-group-xs">
                                                <a href="" class="am-btn am-btn-default am-btn-xs am-text-secondary">
                                                    删除
                                                </a>
                                            </div>

                                        </td>
                                    {% endif %}
                            </tr>
                        {% endfor %}
                    {% endif %}


                    </tbody>
                </table>
                {% if parms_length > 1 %}
                    <div class="am-g">
                        <div class="am-u-sm-12 am-u-md-2 am-fr am-form-group">
                            <div class="am-btn-group am-btn-group-xs am-fr">
                                <a class="am-btn am-btn-default"
                                   href="?next={% url 'rbac:show_permission_menu' %}">取消</a>
                                <input type="submit" class="am-btn am-btn-success">
                            </div>
                        </div>
                    </div>
                {% endif %}

            </form>
        </div>
    </div>
{% endblock %}