CRM/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # 登录，注册，注销，忘记密码，验证码
    path('login/', views.login, name='login'),
    path('get_valid_code/', views.get_valid_code, name='valid_code'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('sign_out/', views.logout, name='sing_out'),

    # 首页
    path('index/', views.index, name='index'),
    path('', views.login),

    # 客户管理
    path('customer/', views.CustomerView.as_view(), name='customer'),
    path('customer/all/', views.CustomerView.as_view(), name='customer_all'),
    path('customer/add/', views.AddEditCustomerView.as_view(), name='customer_add'),
    # 添加公有用户
    path('customer/public_add/', views.AddEditCustomerView.as_view(), name='customer_public_add'),
    path('my_customer/', views.CustomerView.as_view(), name='my_customer'),
    re_path('^customer/edit/(\d+)/$', views.AddEditCustomerView.as_view(), name='customer_edit'),

    # 跟进记录管理
    path('consult_record/', views.ConsultRecordView.as_view(), name='consult_record'),
    path('consult_record/add/', views.AddEditConsultRecordView.as_view(), name='consult_record_add'),
    re_path('^consult_record/edit/(\d+)/$', views.AddEditConsultRecordView.as_view(), name='consult_record_edit'),

    # 财务管理
    path('payment/', views.PaymentView.as_view(), name='payment'),

    # 学生管理
    re_path(r'^', include('student_manage.urls')),

    # 统计数据
    path('count/customer/', views.CountCustomerView.as_view(), name='count_customer'),

    # 权限分配
    re_path(r'^', include(('rbac.urls', 'rbac'),namespace='rbac')),

]

student_manage/urls.py
from django.urls import path, re_path
from student_manage import views

urlpatterns = [

    # 学生成员管理
    path('student/', views.show_student, name='student'),
    path('student/add/', views.AddEditStudentView.as_view(), name='student_add'),
    re_path(r'^student/edit/(\d+)/$', views.AddEditStudentView.as_view(), name='student_edit'),
    re_path(r'^student/del/(\d+)/$', views.del_student, name='student_del'),

    # 班级学习情况管理
    path('class_study_record/', views.ClassStudyRecordView.as_view(), name='class_study_record'),
    path('class_study_record/add/', views.AddEditCsrView.as_view(), name='class_study_record_add'),
    re_path(r'^class_study_record/edit/(\d+)/$', views.AddEditCsrView.as_view(), name='class_study_record_edit'),
    re_path(r'^class_study_record/del/(\d+)/$', views.del_csr, name='class_study_record_del'),

    # 学生学习情况管理
    path('student_study_record/', views.StudentStudyRecordView.as_view(), name='student_study_record'),
    path('student_study_record/add/', views.AddEditSsrView.as_view(), name='student_study_record_add'),
    re_path(r'^student_study_record/edit/(\d+)/$', views.AddEditSsrView.as_view(), name='student_study_record_edit'),
    re_path(r'^student_study_record/del/(\d+)/$', views.del_ssr, name='student_study_record_del'),

    # 录入成绩
    re_path(r'^create_grade/show/(\d+)/$', views.CreateGradeView.as_view(), name='create_grade_show'),
    re_path(r'^create_grade/submit/(\d+)/$', views.CreateGradeView.as_view(), name='create_grade_submit'),

]

student_manage/models.py
from django.db import models
from django.utils.safestring import mark_safe


# Create your models here.


class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='app01.Customer', on_delete=models.CASCADE, null=True,
                                    blank=True)
    class_list = models.ManyToManyField(verbose_name="已报班级", to='app01.ClassList', blank=True)

    emergency_contract = models.CharField(max_length=32, blank=True, null=True, verbose_name='紧急联系人')
    company = models.CharField(verbose_name='公司', max_length=128, blank=True, null=True)
    location = models.CharField(max_length=64, verbose_name='所在区域', blank=True, null=True)
    position = models.CharField(verbose_name='岗位', max_length=64, blank=True, null=True)
    salary = models.IntegerField(verbose_name='薪资', blank=True, null=True)
    welfare = models.CharField(verbose_name='福利', max_length=256, blank=True, null=True)
    date = models.DateField(verbose_name='入职时间', help_text='格式yyyy-mm-dd', blank=True, null=True)
    memo = models.CharField(verbose_name='备注', max_length=256, blank=True, null=True)

    def __str__(self):
        return self.customer.name

    def get_class(self):
        class_list = []
        for item in self.class_list.all():
            class_list.append(str(item))
        return mark_safe('</br>'.join(class_list))


class ClassStudyRecord(models.Model):
    """
    上课记录表 （班级记录）
    """
    class_obj = models.ForeignKey(verbose_name="班级", to="app01.ClassList", on_delete=models.CASCADE)
    day_num = models.IntegerField(verbose_name="节次", help_text=u"此处填写第几节课或第几天课程...,必须为数字")

    teacher = models.ForeignKey(verbose_name="讲师", to='app01.UserInfo', limit_choices_to={"positions__in": [5, 6]},
                                on_delete=models.CASCADE)
    date = models.DateField(verbose_name="上课日期", auto_now_add=True)
    course_title = models.CharField(verbose_name='本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField(verbose_name='本节课程内容概要', blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField(verbose_name='本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField(verbose_name='作业描述', max_length=500, blank=True, null=True)
    exam = models.TextField(verbose_name='踩分点', max_length=300, blank=True, null=True)

    def __str__(self):
        return "{0} day{1}".format(self.class_obj, self.day_num)

    class Meta:
        unique_together = ['class_obj', 'day_num']


class StudentStudyRecord(models.Model):
    '''
    学生学习记录
    '''
    student = models.ForeignKey(verbose_name="学员", to='Student', on_delete=models.CASCADE)
    classstudyrecord = models.ForeignKey(verbose_name="第几天课程", to="ClassStudyRecord", on_delete=models.CASCADE)
    record_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('noshow', "缺勤"),
                      ('leave_early', "早退"),
                      )
    record = models.CharField("上课纪录", choices=record_choices, default="checked", max_length=64)
    score_choices = ((100, 'A+'),
                     (90, 'A'),
                     (85, 'B+'),
                     (80, 'B'),
                     (70, 'B-'),
                     (60, 'C+'),
                     (50, 'C'),
                     (40, 'C-'),
                     (0, ' D'),
                     (-1, 'N/A'),
                     (-100, 'COPY'),
                     (-1000, 'FAIL'),
                     )
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
    homework_note = models.CharField(verbose_name='作业评语', max_length=255, blank=True, null=True)
    note = models.CharField(verbose_name="备注", max_length=255, blank=True, null=True)

    homework = models.FileField(verbose_name='作业文件', blank=True, null=True, default=None)
    stu_memo = models.TextField(verbose_name='学员备注', blank=True, null=True)
    date = models.DateTimeField(verbose_name='提交作业日期', auto_now_add=True)

    def __str__(self):
        return "{0}-{1}".format(self.classstudyrecord, self.student)

    class Meta:
        unique_together = ['student', 'classstudyrecord']

student_manage/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from student_manage.models import Student, ClassStudyRecord, StudentStudyRecord
from app01.utils.pages import Pagination
from django.views import View
from student_manage.utils.forms_check import StudentModelForm, ClassStudyRecordModelForm, StudentStudyRecordMF, \
    CreateGradeMF
import copy


# Create your views here.


def show_student(request):
    all_student = Student.objects.all()
    current_page_num = request.GET.get('page', 1)
    pagination = Pagination(request, current_page_num, all_student)
    page_html, all_student, counter = pagination.page_html()
    return render(request, 'student.html',
                  {'page_html': page_html,
                   'all_student': all_student,
                   'counter': counter,
                   })


class AddEditStudentView(View):
    """学生编辑，添加"""

    def get(self, request, sid=None):
        student_obj = Student.objects.filter(pk=sid).first()
        forms = StudentModelForm(instance=student_obj)
        return render(request, 'add_edit_consult_record.html', {'forms': forms, 'student_obj': student_obj})

    def post(self, request, sid=None):
        student_obj = Student.objects.filter(pk=sid).first()
        forms = StudentModelForm(instance=student_obj, data=request.POST)
        if forms.is_valid():
            forms.save()
            return redirect(request.GET.get('next', 'student'))
        else:
            return render(request, 'add_edit_consult_record.html', {'forms': forms, 'student_obj': student_obj})


def del_student(request, sid):
    """
    删除学生
    :param request:
    :param sid:
    :return:
    """
    Student.objects.filter(pk=sid).delete()
    return redirect('student')


class ClassStudyRecordView(View):
    def get(self, request):
        all_csr = ClassStudyRecord.objects.all()
        current_page_num = request.GET.get('page', 1)
        pagination = Pagination(request, current_page_num, all_csr)
        page_html, all_csr, counter = pagination.page_html()
        return render(request, 'class_study_record.html',
                      {'page_html': page_html,
                       'all_csr': all_csr,
                       'counter': counter,
                       })

    def post(self, request):
        select_method = request.POST.get('select_method')
        if hasattr(self, select_method):
            func = getattr(self, select_method)
            func(request)
            return redirect('class_study_record')

        else:
            return HttpResponse('非法的操作')

    def batch_create(self, request):
        csr_list = request.POST.getlist('checked_csr')
        for csr in csr_list:
            kclass = ClassStudyRecord.objects.filter(pk=csr).values('class_obj__student')
            for item in kclass:
                try:
                    StudentStudyRecord.objects.create(student_id=item['class_obj__student'],
                                                      classstudyrecord_id=csr)
                except Exception:
                    pass


class AddEditCsrView(View):
    """班级学习进度编辑，添加"""

    def get(self, request, cid=None):
        csr_obj = ClassStudyRecord.objects.filter(pk=cid).first()
        forms = ClassStudyRecordModelForm(instance=csr_obj)
        return render(request, 'add_edit_consult_record.html', {'forms': forms, 'csr_obj': csr_obj})

    def post(self, request, cid=None):
        csr_obj = ClassStudyRecord.objects.filter(pk=cid).first()
        forms = ClassStudyRecordModelForm(instance=csr_obj, data=request.POST)
        if forms.is_valid():
            forms.save()
            return redirect(request.GET.get('next', 'class_study_record'))
        else:
            return render(request, 'add_edit_consult_record.html', {'forms': forms, 'csr_obj': csr_obj})


def del_csr(request, sid):
    ClassStudyRecord.objects.filter(pk=sid).delete()
    return redirect('class_study_record')


class StudentStudyRecordView(View):
    """查看学生学习进度"""

    def get(self, request):
        all_ssr = StudentStudyRecord.objects.all()
        current_page_num = request.GET.get('page', 1)
        pagination = Pagination(request, current_page_num, all_ssr)
        page_html, all_ssr, counter = pagination.page_html()
        return render(request, 'student_study_record.html',
                      {'page_html': page_html,
                       'all_ssr': all_ssr,
                       'counter': counter,
                       })


class AddEditSsrView(View):
    """学生学习进度编辑，添加"""

    def get(self, request, cid=None):
        ssr_obj = StudentStudyRecord.objects.filter(pk=cid).first()
        forms = StudentStudyRecordMF(instance=ssr_obj)
        return render(request, 'add_edit_consult_record.html', {'forms': forms, 'ssr_obj': ssr_obj})

    def post(self, request, cid=None):
        ssr_obj = StudentStudyRecord.objects.filter(pk=cid).first()
        forms = StudentStudyRecordMF(instance=ssr_obj, data=request.POST)
        if forms.is_valid():
            forms.save()
            return redirect(request.GET.get('next', 'student_study_record'))
        else:
            return render(request, 'add_edit_consult_record.html', {'forms': forms, 'ssr_obj': ssr_obj})


def del_ssr(request, sid):
    """
    删除学生学习记录
    :param request:
    :param sid:
    :return:
    """
    StudentStudyRecord.objects.filter(pk=sid).delete()
    return redirect('student_study_record')


class CreateGradeView(View):
    def get(self, request, cid):
        ssr_obj = StudentStudyRecord.objects.filter(classstudyrecord_id=cid)
        ssr_obj = copy.deepcopy(ssr_obj)
        title = ClassStudyRecord.objects.filter(pk=cid).first()
        for item in ssr_obj:
            item.forms = CreateGradeMF(instance=item)
        current_page_num = request.GET.get('page', 1)
        pagination = Pagination(request, current_page_num, ssr_obj)
        page_html, ssr_obj, counter = pagination.page_html()

        return render(request, 'create_grade.html',
                      {'page_html': page_html,
                       'ssr_obj': ssr_obj,
                       'counter': counter,
                       'title': title,
                       })

    def post(self, request, cid):
        data_list = zip(request.POST.getlist('checked_csr'), request.POST.getlist('score'),
                        request.POST.getlist('homework_note'))
        for data in data_list:
            obj = StudentStudyRecord.objects.filter(pk=data[0]).first()
            finally_data = {'score': data[1],
                            'homework_note': data[2]}
            forms = CreateGradeMF(instance=obj, data=finally_data)
            if forms.is_valid():
                forms.save()
            else:
                return HttpResponse('数据不合法')
        return redirect(request.GET.get('next', 'class_study_record'))

student_manage/templates/add_edit_csr.html
{% extends 'base.html' %}

{% block content %}

    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf">
            <strong class="am-text-primary am-text-lg">
                {% if csr_obj %}
                    编辑班级学习进度
                {% else %}
                    添加班级学习进度
                {% endif %}

            </strong>
            <small>学习情况管理</small>
        </div>
    </div>

    <hr>
    <form action="" class="am-form" method="post">
        {% csrf_token %}
        <div class="am-tabs am-margin" data-am-tabs>
            <ul class="am-tabs-nav am-nav am-nav-tabs">
                <li class="am-active"><a href="#tab1">基本信息</a></li>
            </ul>

            <div class="am-tabs-bd">
                <div class="am-tab-panel am-fade am-in am-active" id="tab1">

                    {% for form in forms %}
                        <div class="am-g am-margin-top">
                            <div class="am-u-sm-4 am-u-md-2 am-text-right">
                                {{ form.label }}
                            </div>
                            <div class="am-u-sm-8 am-u-md-4">
                                {{ form }}
                            </div>
                            <div class="am-hide-sm-only am-u-md-6"></div>
                        </div>
                    {% endfor %}

                </div>

            </div>
        </div>

        <div class="am-margin">
            <input type="submit" class="am-btn am-btn-primary am-btn-xs" value="提交保存">
            <button type="button" class="am-btn am-btn-primary am-btn-xs">放弃保存</button>
        </div>
    </form>
{% endblock %}

student_manage/templates/add_edit_ssr.html
{% extends 'base.html' %}

{% block content %}

    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf">
            <strong class="am-text-primary am-text-lg">
                {% if ssr_obj %}
                    编辑班级学习进度
                {% else %}
                    添加班级学习进度
                {% endif %}

            </strong>
            <small>学习情况管理</small>
        </div>
    </div>

    <hr>
    <form action="" class="am-form" method="post">
        {% csrf_token %}
        <div class="am-tabs am-margin" data-am-tabs>
            <ul class="am-tabs-nav am-nav am-nav-tabs">
                <li class="am-active"><a href="#tab1">基本信息</a></li>
            </ul>

            <div class="am-tabs-bd">
                <div class="am-tab-panel am-fade am-in am-active" id="tab1">

                    {% for form in forms %}
                        <div class="am-g am-margin-top">
                            <div class="am-u-sm-4 am-u-md-2 am-text-right">
                                {{ form.label }}
                            </div>
                            <div class="am-u-sm-8 am-u-md-4">
                                {{ form }}
                            </div>
                            <div class="am-hide-sm-only am-u-md-6"></div>
                        </div>
                    {% endfor %}

                </div>

            </div>
        </div>

        <div class="am-margin">
            <input type="submit" class="am-btn am-btn-primary am-btn-xs" value="提交保存">
            <button type="button" class="am-btn am-btn-primary am-btn-xs">放弃保存</button>
        </div>
    </form>
{% endblock %}

student_manage/templates/add_edit_student.html
{% extends 'base.html' %}

{% block content %}

    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf">
            <strong class="am-text-primary am-text-lg">
                {% if student_obj %}
                    编辑学生
                {% else %}
                    添加学生
                {% endif %}

            </strong>
            <small>学生管理</small>
        </div>
    </div>

    <hr>
    <form action="" class="am-form" method="post">
        {% csrf_token %}
        <div class="am-tabs am-margin" data-am-tabs>
            <ul class="am-tabs-nav am-nav am-nav-tabs">
                <li class="am-active"><a href="#tab1">基本信息</a></li>
            </ul>

            <div class="am-tabs-bd">
                <div class="am-tab-panel am-fade am-in am-active" id="tab1">

                    {% for form in forms %}
                        <div class="am-g am-margin-top">
                            <div class="am-u-sm-4 am-u-md-2 am-text-right">
                                {{ form.label }}
                            </div>
                            <div class="am-u-sm-8 am-u-md-4">
                                {{ form }}
                            </div>
                            <div class="am-hide-sm-only am-u-md-6"></div>
                        </div>
                    {% endfor %}

                </div>

            </div>
        </div>

        <div class="am-margin">
            <input type="submit" class="am-btn am-btn-primary am-btn-xs" value="提交保存">
            <button type="button" class="am-btn am-btn-primary am-btn-xs">放弃保存</button>
        </div>
    </form>
{% endblock %}

student_manage/templates/class_study_record.html
{% extends 'base.html' %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">班级课程进度</strong> /
            <small>班级学习管理</small>
        </div>
    </div>

    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    <a class="am-btn am-btn-default"
                       href="{% url 'class_study_record_add' %}?next={{ request.path }}"><span
                            class="am-icon-plus"></span>
                        新增</a>
                    <button type="button" class="am-btn am-btn-default"><span class="am-icon-trash-o"></span> 删除
                    </button>
                </div>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-3 am-form-group">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form" method="post">
                {% csrf_token %}
                <div class="am-u-sm-12 am-u-md-3 am-form-group">
                    <div class="am-input-group am-input-group-sm">
                        <select data-am-selected="{btnSize: 'sm'}" name="select_method">
                            <option value="batch_create">批量创建学习记录</option>
                            <option value="option2">批量删除</option>
                        </select>
                        <span class="am-input-group-btn">
                            <input class="am-btn am-btn-success" type="submit" value="go">
                        </span>
                    </div>
                </div>
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="table-check">
                            <input type="checkbox"/>
                        </th>
                        <th class="am-text-center">ID</th>
                        <th class="am-text-center">班级</th>
                        <th class="am-text-center">节次</th>
                        <th class="am-text-center">讲师</th>
                        <th class="am-text-center">考勤</th>
                        <th class="am-text-center">成绩</th>
                        <th class="am-text-center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for csr in all_csr %}
                        <tr>
                            <td><input type="checkbox" value="{{ csr.pk }}" name="checked_csr"/></td>
                            <td>{{ csr.page_num }}</td>
                            <td>{{ csr.class_obj }}</td>
                            <td>{{ csr.day_num }}天</td>
                            <td>{{ csr.teacher }}</td>
                            <td><a href="">考勤</a></td>
                            <td><a href="{% url 'create_grade_show' csr.pk %}?next={{ request.path }}">录入成绩</a></td>
                            <td>
                                <div class="am-btn-toolbar">
                                    <div class="am-btn-group am-btn-group-xs">
                                        <a href="{% url 'class_study_record_edit' csr.pk %}?next={{ request.path }}"
                                           class="am-btn am-btn-default am-btn-xs am-text-secondary"><span
                                                class="am-icon-pencil-square-o"></span> 编辑
                                        </a>
                                        <a href="{% url 'class_study_record_del' csr.pk %}"
                                           class="am-btn am-btn-danger am-btn-xs"><span
                                                class="am-icon-trash-o"></span> 删除
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
                <div class="am-cf">
                    共 {{ counter }} 条记录
                    <div class="am-fr am-center">
                        <ul class="am-pagination">
                            {{ page_html|safe }}
                        </ul>
                    </div>
                </div>
                <hr/>
            </form>
        </div>

    </div>
{% endblock %}


{% block javascript %}
    <script src="/static/js/app.js"></script>
{% endblock %}

student_manage/templates/create_grade.html
{% extends 'base.html' %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">录入成绩</strong> /
            <small>{{ title }}</small>
        </div>
    </div>

    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    <a class="am-btn am-btn-default"
                       href=""><span
                            class="am-icon-plus"></span>
                        新增</a>
                    <button type="button" class="am-btn am-btn-default"><span class="am-icon-trash-o"></span> 删除
                    </button>
                </div>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-3 am-form-group">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form" method="post">
                {% csrf_token %}
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="table-check">
                            <input type="checkbox"/>
                        </th>
                        <th class="am-text-center">ID</th>
                        <th class="am-text-center">姓名</th>
                        <th class="am-text-center">考勤</th>
                        <th class="am-text-center">成绩</th>
                        <th class="am-text-center">批语</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ssr in ssr_obj %}
                        <tr>
                            <td><input type="checkbox" value="{{ ssr.pk }}" name="checked_csr" checked/></td>
                            <td>{{ ssr.page_num }}</td>
                            <td>{{ ssr.student }}</td>
                            <td>{{ ssr.get_record_display }}</td>
                            <td>{{ ssr.forms.score }}</td>
                            <td>{{ ssr.forms.homework_note }}</td>
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
                <div class="am-cf">
                    共 {{ counter }} 条记录
                    <div class="am-fr am-center">
                        <ul class="am-pagination">
                            {{ page_html|safe }}
                        </ul>
                    </div>
                </div>
                <hr/>
                <input type="submit" class="am-btn am-btn-success" value="提交">
            </form>
        </div>

    </div>
{% endblock %}


{% block javascript %}
    <script src="/static/js/app.js"></script>
{% endblock %}

student_manage/templates/student_study_record.html
{% extends 'base.html' %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">学生课程进度</strong> /
            <small>学生学习管理</small>
        </div>
    </div>

    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    <a class="am-btn am-btn-default"
                       href="{% url 'student_study_record_add' %}?next={{ request.path }}"><span
                            class="am-icon-plus"></span>
                        新增</a>
                    <button type="button" class="am-btn am-btn-default"><span class="am-icon-trash-o"></span> 删除
                    </button>
                </div>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-3 am-form-group">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form" method="post">
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="table-check">
                            <input type="checkbox"/>
                        </th>
                        <th class="am-text-center">ID</th>
                        <th class="am-text-center">姓名</th>
                        <th class="am-text-center">节次</th>
                        <th class="am-text-center">上课记录</th>
                        <th class="am-text-center">分数</th>
                        <th class="am-text-center">作业评语</th>
                        <th class="am-text-center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ssr in all_ssr %}
                        <tr>
                            <td><input type="checkbox" value="{{ ssr.pk }}" name="checked_csr"/></td>
                            <td>{{ ssr.page_num }}</td>
                            <td>{{ ssr.student }}</td>
                            <td>{{ ssr.classstudyrecord }}天</td>
                            <td>{{ ssr.get_record_display }}</td>
                            <td>{{ ssr.score }}</td>
                            <td>{{ ssr.homework_note }}</td>
                            <td>
                                <div class="am-btn-toolbar">
                                    <div class="am-btn-group am-btn-group-xs">
                                        <a href="{% url 'student_study_record_edit' ssr.pk %}?next={{ request.path }}"
                                           class="am-btn am-btn-default am-btn-xs am-text-secondary"><span
                                                class="am-icon-pencil-square-o"></span> 编辑
                                        </a>
                                        <a href="{% url 'student_study_record_del' ssr.pk %}"
                                           class="am-btn am-btn-danger am-btn-xs"><span
                                                class="am-icon-trash-o"></span> 删除
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
                <div class="am-cf">
                    共 {{ counter }} 条记录
                    <div class="am-fr am-center">
                        <ul class="am-pagination">
                            {{ page_html|safe }}
                        </ul>
                    </div>
                </div>
                <hr/>
            </form>
        </div>

    </div>
{% endblock %}


{% block javascript %}
    <script src="/static/js/app.js"></script>
{% endblock %}