CRM/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # 登录，注册，注销，忘记密码，验证码
    path('login/', views.login, name='login'),
    path('get_valid_code/', views.get_valid_code, name='valid_code'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('sign_out/', views.logout, name='sing_out'),

    # 首页
    path('index/', views.index, name='index'),
    path('', views.login),

    # 客户管理
    path('customer/', views.CustomerView.as_view(), name='customer'),
    path('customer/all/', views.CustomerView.as_view(), name='customer_all'),
    path('customer/add/', views.AddEditCustomerView.as_view(), name='customer_add'),
    # 添加公有用户
    path('customer/public_add/', views.AddEditCustomerView.as_view(), name='customer_public_add'),
    path('my_customer/', views.CustomerView.as_view(), name='my_customer'),
    re_path('^customer/edit/(\d+)/$', views.AddEditCustomerView.as_view(), name='customer_edit'),

    # 跟进记录管理
    path('consult_record/', views.ConsultRecordView.as_view(), name='consult_record'),
    path('consult_record/add/', views.AddEditConsultRecordView.as_view(), name='consult_record_add'),
    re_path('^consult_record/edit/(\d+)/$', views.AddEditConsultRecordView.as_view(), name='consult_record_edit'),

    # 财务管理
    path('payment/', views.PaymentView.as_view(), name='payment'),

    # 学生管理
    re_path(r'^', include('student_manage.urls')),

    # 统计数据
    path('count/customer/', views.CountCustomerView.as_view(), name='count_customer'),

    # 权限分配
    re_path(r'^', include(('rbac.urls', 'rbac'),namespace='rbac')),

]

app01/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe


# Create your models here.


class UserInfo(AbstractUser):
    gender = models.IntegerField(choices=((1, '男'), (0, '女')), default=1)
    tel = models.CharField(max_length=32, null=True)
    positions = models.ManyToManyField('Position')


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(verbose_name='部门名称', max_length=32)

    def __str__(self):
        return self.name


class Position(models.Model):
    """
    职位表
    """
    title = models.CharField(verbose_name='职位名称', max_length=32)
    depart = models.ForeignKey('Department', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,
                                       on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,
                                   on_delete=models.CASCADE)
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级")
    deal_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_class(self):
        class_list = []
        for item in self.class_list.all():
            class_list.append(str(item))
        return mark_safe('</br>'.join(class_list))


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    # 元类信息：联合唯一
    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}期({})".format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户", on_delete=models.CASCADE)
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records', on_delete=models.CASCADE)
    date = models.DateTimeField("跟进日期", auto_now_add=True)

    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    def __str__(self):
        return str(self.customer) + str(self.consultant)


class Enrollment(models.Model):
    customer = models.ForeignKey('Customer', verbose_name='客户名称', on_delete=models.CASCADE)
    why_us = models.TextField('为什么报名', max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField('学完想达到的具体期望', max_length=1024, blank=True, null=True)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name='报名日期')
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    school = models.ForeignKey('Campuses', on_delete=models.CASCADE)
    enrollment_class = models.ForeignKey('ClassList', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('enrollment_class', 'customer')

    def __str__(self):
        return self.customer

templates/base.html
<!doctype html>
<html class="no-js fixed-layout">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Amaze UI Admin index Examples</title>
    <meta name="description" content="这是一个 index 页面">
    <meta name="keywords" content="index">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link rel="icon" type="image/png" href="/static/i/favicon.png">
    <link rel="apple-touch-icon-precomposed" href="/static/i/app-icon72x72@2x.png">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="stylesheet" href="/static/css/amazeui.min.css"/>
    <link rel="stylesheet" href="/static/css/admin.css">
    {% block style %}
    
    {% endblock %}
    <style>
        .url-active {
            background: #0bb59b !important;
        }
    </style>
</head>
<body>
<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器，Amaze UI 暂不支持。 请 <a href="http://browsehappy.com/" target="_blank">升级浏览器</a>
  以获得更好的体验！</p>
<![endif]-->

<header class="am-topbar am-topbar-inverse admin-header">
    <div class="am-topbar-brand">
        <strong>Amaze UI</strong>
        <small>CRM</small>
    </div>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only"
            data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span
            class="am-icon-bars"></span></button>

    <div class="am-collapse am-topbar-collapse" id="topbar-collapse">

        <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
            <li><a href="javascript:;"><span class="am-icon-envelope-o"></span> 收件箱 <span
                    class="am-badge am-badge-warning">5</span></a></li>
            <li class="am-dropdown" data-am-dropdown>
                <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                    <span class="am-icon-users"></span> {{ request.user }} <span class="am-icon-caret-down"></span>
                </a>
                <ul class="am-dropdown-content">
                    <li><a href="#"><span class="am-icon-user"></span> 资料</a></li>
                    <li><a href="#"><span class="am-icon-cog"></span> 设置</a></li>
                    <li><a href="{% url 'sing_out' %}"><span class="am-icon-power-off"></span> 登出</a></li>
                </ul>
            </li>
            <li class="am-hide-sm-only"><a href="javascript:;" id="admin-fullscreen"><span
                    class="am-icon-arrows-alt"></span> <span class="admin-fullText">开启全屏</span></a></li>
        </ul>
    </div>
</header>

<div class="am-cf admin-main">
    <!-- sidebar start -->
    <div class="admin-sidebar am-offcanvas" id="admin-offcanvas">
        <div class="am-offcanvas-bar admin-offcanvas-bar">
            {% load show_menu %}
            {% show_menu_list request %}

            <div class="am-panel am-panel-default admin-sidebar-panel">
                <div class="am-panel-bd">
                    <p><span class="am-icon-bookmark"></span> 公告</p>
                    <p>时光静好，与君语；细水流年，与君同。—— Amaze UI</p>
                </div>
            </div>

            <div class="am-panel am-panel-default admin-sidebar-panel">
                <div class="am-panel-bd">
                    <p><span class="am-icon-tag"></span> wiki</p>
                    <p>Welcome to the Amaze UI wiki!</p>
                </div>
            </div>
        </div>
    </div>
    <!-- sidebar end -->

    <!-- content start -->
    <div class="admin-content">
        <div class="admin-content-body">
            {% block content %}

            {% endblock %}
        </div>

        <footer class="admin-content-footer">
            <hr>
            <p class="am-padding-left">© 2014 AllMobilize, Inc. Licensed under MIT license.</p>
        </footer>
    </div>
    <!-- content end -->

</div>

<a href="#" class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu"
   data-am-offcanvas="{target: '#admin-offcanvas'}"></a>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/static/js/jquery.min.js"></script>
<!--<![endif]-->
<script src="/static/js/amazeui.min.js"></script>
<script src="/static/js/app.js"></script>
{% block javascript %}

{% endblock %}
</body>
</html>

templates/consult_record.html
{% extends 'base.html' %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">跟进记录</strong> /
            <small>客户管理</small>
        </div>
    </div>

    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    <a class="am-btn am-btn-default" href="{% url 'consult_record_add' %}?next={{ request.path }}"><span
                            class="am-icon-plus"></span>
                        新增</a>
                    <button type="button" class="am-btn am-btn-default"><span class="am-icon-trash-o"></span> 删除
                    </button>
                </div>
            </div>
        </div>
        <!--
        <div class="am-u-sm-12 am-u-md-3">
            <div class="am-form-group">
                <select data-am-selected="{btnSize: 'sm'}">
                    <option value="option1">所有类别</option>
                    <option value="option2">IT业界</option>
                    <option value="option3">数码产品</option>
                    <option value="option3">笔记本电脑</option>
                    <option value="option3">平板电脑</option>
                    <option value="option3">只能手机</option>
                    <option value="option3">超极本</option>
                </select>
            </div>
        </div>
        -->

        <div class="am-u-sm-12 am-u-md-3 am-form-group">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form">
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="table-check">
                            <input type="checkbox"/>
                        </th>
                        <th class="am-text-center">ID</th>
                        <th class="am-text-center">客户姓名</th>
                        <th class="am-text-center">当前状态</th>
                        <th class="am-text-center">内容</th>
                        <th class="am-text-center">日期</th>
                        <th class="am-text-center">销售</th>
                        <th class="am-text-center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in consult_record %}
                        <tr>
                            <td><input type="checkbox" value="{{ item.pk }}"/></td>
                            <td>{{ item.page_num }}</td>
                            <td>{{ item.customer }}</td>
                            <td>{{ item.get_status_display }}</td>
                            <td>{{ item.note }}</td>
                            <td>{{ item.date|date:'Y-m-d' }}</td>
                            <td>{{ item.consultant }}</td>

                            <td>
                                <div class="am-btn-toolbar">
                                    <div class="am-btn-group am-btn-group-xs">
                                        <a href="{% url 'consult_record_edit' item.pk %}?next={{ request.path }}"
                                           class="am-btn am-btn-default am-btn-xs am-text-secondary"><span
                                                class="am-icon-pencil-square-o"></span> 编辑
                                        </a>
                                        <button class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span
                                                class="am-icon-trash-o"></span> 删除
                                        </button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
                <div class="am-cf">
                    共 {{ counter }} 条记录
                    <div class="am-fr am-center">
                        <ul class="am-pagination">
                            {{ page_html|safe }}
                        </ul>
                    </div>
                </div>
                <hr/>
            </form>
        </div>

    </div>
{% endblock %}

templates/count_customer.html
{% extends 'base.html' %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">销售统计</strong> /
            <small>统计管理</small>
        </div>
    </div>

    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    {% csrf_token %}
                    <a class="am-btn am-btn-default" href="?date=today"><span
                            class="am-icon-plus"></span>
                        今日成单数据</a>
                    <a class="am-btn am-btn-default" href="?date=yesterday"><span
                            class="am-icon-plus"></span>
                        昨天成单数据</a>
                    <a class="am-btn am-btn-default" href="?date=week"><span
                            class="am-icon-plus"></span>
                        一周成单数据</a>
                    <a class="am-btn am-btn-default" href="?date=month"><span
                            class="am-icon-plus"></span>
                        一月成单数据</a>

                </div>
            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-3">
            <div class="am-form-group">
                <select data-am-selected="{btnSize: 'sm'}">
                    <option value="option1">所有类别</option>
                    <option value="option2">IT业界</option>
                    <option value="option3">数码产品</option>
                    <option value="option3">笔记本电脑</option>
                    <option value="option3">平板电脑</option>
                    <option value="option3">只能手机</option>
                    <option value="option3">超极本</option>
                </select>
            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-3">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form">
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="am-text-center">ID</th>
                        <th class="am-text-center">客户姓名</th>
                        <th class="am-text-center">性别</th>
                        <th class="am-text-center">客户来源</th>
                        <th class="am-text-center">销售</th>
                        <th class="am-text-center">成交日期</th>
                        <th class="am-text-center">所报班级</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in customer_obj %}
                        <tr>
                            <td>{{ customer.page_num }}</td>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.get_sex_display }}</td>
                            <td>{{ customer.get_source_display }}</td>
                            <td>{{ customer.consultant }}</td>
                            <td>{{ customer.deal_date|date:'Y-m-d' }}</td>
                            <td>{{ customer.get_class }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
                <div class="am-cf">
                    共 {{ counter }} 条记录
                    <div class="am-fr am-center">
                        <ul class="am-pagination">
                            {{ page_html|safe }}
                        </ul>
                    </div>
                </div>
                <hr/>
            </form>
        </div>
    </div>
    <div id="container" style="width:600px;height:400px"></div>
{% endblock %}

{% block javascript %}
    <script src="/static/highchart/highcharts.js"></script>
    <script>
        var chart = Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: '统计成单量'
            },
            subtitle: {
                text: '数据截止 2017-03，来源: <a href="https://en.wikipedia.org/wiki/List_of_cities_proper_by_population">Wikipedia</a>'
            },
            xAxis: {
                type: 'category',
                labels: {
                    rotation: 0  // 设置轴标签旋转角度
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: '成单数'
                }
            },
            legend: {
                enabled: false
            },
            tooltip: {
                pointFormat: '成单人数: <b>{point.y} 单</b>'
            },
            series: [{
                name: '总人口',
                data: {{ ret|safe }},
                dataLabels: {
                    enabled: true,
                    rotation: -90,
                    color: '#FFFFFF',
                    align: 'right',
                    format: '{point.y:.1f}', // :.1f 为保留 1 位小数
                    y: 10
                }
            }]
        });

    </script>
{% endblock %}

templates/customer.html
{% extends 'base.html' %}

{% block style %}
    <style>
        .btn-font-size {
            font-size: 1.2rem !important;
        }

        .condition-btn {
            margin-bottom: 5px;
        }

        .condition-box {
            border: 1px solid #ddd;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="am-cf am-padding am-padding-bottom-0">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">{{ label }}</strong> /
            <small>客户管理</small>
        </div>
    </div>
    <div class="am-g condition-box">
        <div class="am-u-md-12 condition-btn">
            <span class="btn-font-size">已报班级</span>
            <a href="" class="am-btn am-btn-success btn-font-size">全部</a>
            {% for item in class_list %}
                <a href="" class="am-btn btn-font-size">{{ item }}</a>
            {% endfor %}
        </div>

        <div class="am-u-md-12 condition-btn">
            <span class="btn-font-size">状态</span>
            <a href="" class="am-btn am-btn-success btn-font-size">全部</a>
            {% for item in status %}
                <a href="?a=123" class="am-btn btn-font-size">{{ item.1 }}</a>
            {% endfor %}
        </div>

        <div class="am-u-md-12 condition-btn">
            <span class="btn-font-size">销售</span>
            <a href="?/consultant_id=" class="am-btn am-btn-success btn-font-size">全部</a>
            {% for item in consultrecord_list %}
                <a href="?consultant_id={{ item.pk }}&{{ url_parms }}"
                   class="am-btn btn-font-size">{{ item.username }}</a>
            {% endfor %}
        </div>

    </div>
    <hr>

    <div class="am-g">
        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    {% csrf_token %}
                    <a class="am-btn am-btn-default"
                       href="{% url 'customer_add' %}?next={{ request.path }}"><span
                            class="am-icon-plus"></span>
                        新增</a>
                </div>
            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-3">
            <div class="am-form-group">
                <select data-am-selected="{btnSize: 'sm'}">
                    <option value="option1">所有类别</option>
                    <option value="option2">IT业界</option>
                    <option value="option3">数码产品</option>
                    <option value="option3">笔记本电脑</option>
                    <option value="option3">平板电脑</option>
                    <option value="option3">只能手机</option>
                    <option value="option3">超极本</option>
                </select>
            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-3">
            <div class="am-input-group am-input-group-sm">
                <input type="text" class="am-form-field">
                <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
            </div>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form">
                <table class="am-table am-table-striped am-table-bordered am-table-hover table-main am-text-center">
                    <thead>
                    <tr>
                        <th class="table-check">
                            <input type="checkbox"/>
                        </th>
                        <th class="am-text-center">ID</th>
                        <th class="am-text-center">客户姓名</th>
                        <th class="am-text-center">性别</th>
                        <th class="am-text-center">QQ</th>
                        <th class="am-text-center">手机号</th>
                        <th class="am-text-center">客户来源</th>
                        <th class="am-text-center">当前状态</th>
                        <th class="am-text-center">销售</th>
                        <th class="am-text-center">所报班级</th>
                        <th class="am-text-center">跟进记录</th>

                        <th class="am-text-center">操作</th>


                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in customer_list %}
                        <tr>
                            <td><input type="checkbox" id="" value="{{ customer.pk }}"/></td>
                            <td>{{ customer.page_num }}</td>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.get_sex_display }}</td>
                            <td>{{ customer.qq }}</td>
                            <td>{{ customer.phone|default:'暂无' }}</td>
                            <td>{{ customer.get_source_display }}</td>
                            <td>{{ customer.get_status_display }}</td>
                            <td>{{ customer.consultant|default:'暂无' }}</td>
                            <td>{{ customer.get_class }}</td>
                            <td><a href="{% url 'consult_record' %}?cid={{ customer.pk }}">跟进记录</a></td>
                            <td>
                                <div class="am-btn-toolbar">
                                    <div class="am-btn-group am-btn-group-xs">

                                        <a href="{% url 'customer_edit' customer.pk %}?next={{ request.path }}&page={{ current_page_num }}"
                                           class="am-btn am-btn-default am-btn-xs am-text-secondary"><span
                                                class="am-icon-pencil-square-o"></span> 编辑
                                        </a>
                                        <button class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span
                                                class="am-icon-trash-o"></span> 删除
                                        </button>
                                    </div>
                                </div>
                            </td>

                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
                <div class="am-cf">
                    共 {{ counter }} 条记录
                    <div class="am-fr am-center">
                        <ul class="am-pagination">
                            {{ page_html|safe }}
                        </ul>
                    </div>
                </div>
                <hr/>
            </form>
        </div>
    </div>
{% endblock %}


{% block javascript %}
    <script>
        $(function () {
            $('#reverse-gs').click(function () {
                $.ajax({
                    url: '',
                    type: 'post',
                    data: JSON.stringify({
                        method: $('#reverse-gs').attr('method'),
                        data: 123
                    })

                })
            })
        })
    </script>
{% endblock %}

templates/payment.html
{% extends 'base.html' %}

{% block content %}
    <h1>缴费列表</h1>
{% endblock %}